services:
  gasp-avs:
    image: gaspxyz/gasp-avs:16323b6a2f7f01eb41ed8428a74758c8fd1c635e
    restart: unless-stopped
    env_file: .env
    volumes:
      - gasp-avs-data:/data
    environment:
      # Use RUST_LOG to control logging levels
      RUST_LOG: ${RUST_LOG:-info,substrate=warn}

volumes:
  gasp-avs-data: