services:
  gasp-avs:
    image: gaspxyz/gasp-avs:7387cc389edd5792421456e72c2096b1712d83b5
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./data:/data
      - ${ECDSA_KEY_FILE_HOST:-./operator_keys/ecdsa.key.json}:/app/operator_keys/ecdsa_key.json:readonly
      - ${BLS_KEY_FILE_HOST:-./operator_keys/bls.key.json}:/app/operator_keys/bls_key.json:readonly
    environment:
      AVS_BLOCK_VALIDATION_PERIOD: ${AVS_BLOCK_VALIDATION_PERIOD:-100}
      AVS_DEBOUNCE_RPC: ${AVS_DEBOUNCE_RPC:-20}
      AVS_KICK_PERIOD: ${AVS_KICK_PERIOD:-25}
      AVS_TASK_EXPIRATION: ${AVS_TASK_EXPIRATION:-300}
      AVS_UPDATE_STAKE_PERIOD: ${AVS_UPDATE_STAKE_PERIOD:-150}
      # Use RUST_LOG to control logging levels
      RUST_LOG: ${RUST_LOG:-info,substrate=warn}
